// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: GameMessage.proto

package Messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NavV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *NavV3) Reset() {
	*x = NavV3{}
	mi := &file_GameMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavV3) ProtoMessage() {}

func (x *NavV3) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavV3.ProtoReflect.Descriptor instead.
func (*NavV3) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{0}
}

func (x *NavV3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NavV3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NavV3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type PathTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []*NavV3 `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *PathTest) Reset() {
	*x = PathTest{}
	mi := &file_GameMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathTest) ProtoMessage() {}

func (x *PathTest) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathTest.ProtoReflect.Descriptor instead.
func (*PathTest) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{1}
}

func (x *PathTest) GetPaths() []*NavV3 {
	if x != nil {
		return x.Paths
	}
	return nil
}

type PlayerPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y         float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z         float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Fx        float32 `protobuf:"fixed32,4,opt,name=fx,proto3" json:"fx,omitempty"`
	Fy        float32 `protobuf:"fixed32,5,opt,name=fy,proto3" json:"fy,omitempty"`
	Fz        float32 `protobuf:"fixed32,6,opt,name=fz,proto3" json:"fz,omitempty"`
	PlayerId  string  `protobuf:"bytes,7,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Speed     float32 `protobuf:"fixed32,8,opt,name=speed,proto3" json:"speed,omitempty"`
	RotationY float32 `protobuf:"fixed32,9,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
}

func (x *PlayerPosition) Reset() {
	*x = PlayerPosition{}
	mi := &file_GameMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPosition) ProtoMessage() {}

func (x *PlayerPosition) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPosition.ProtoReflect.Descriptor instead.
func (*PlayerPosition) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerPosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerPosition) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerPosition) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerPosition) GetFx() float32 {
	if x != nil {
		return x.Fx
	}
	return 0
}

func (x *PlayerPosition) GetFy() float32 {
	if x != nil {
		return x.Fy
	}
	return 0
}

func (x *PlayerPosition) GetFz() float32 {
	if x != nil {
		return x.Fz
	}
	return 0
}

func (x *PlayerPosition) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerPosition) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PlayerPosition) GetRotationY() float32 {
	if x != nil {
		return x.RotationY
	}
	return 0
}

type SpawnMyPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y         float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z         float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	RotationY float32 `protobuf:"fixed32,4,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
}

func (x *SpawnMyPlayer) Reset() {
	*x = SpawnMyPlayer{}
	mi := &file_GameMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnMyPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnMyPlayer) ProtoMessage() {}

func (x *SpawnMyPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnMyPlayer.ProtoReflect.Descriptor instead.
func (*SpawnMyPlayer) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{3}
}

func (x *SpawnMyPlayer) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SpawnMyPlayer) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SpawnMyPlayer) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *SpawnMyPlayer) GetRotationY() float32 {
	if x != nil {
		return x.RotationY
	}
	return 0
}

type SpawnOtherPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId  string  `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	X         float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y         float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z         float32 `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	RotationY float32 `protobuf:"fixed32,5,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
}

func (x *SpawnOtherPlayer) Reset() {
	*x = SpawnOtherPlayer{}
	mi := &file_GameMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnOtherPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnOtherPlayer) ProtoMessage() {}

func (x *SpawnOtherPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnOtherPlayer.ProtoReflect.Descriptor instead.
func (*SpawnOtherPlayer) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{4}
}

func (x *SpawnOtherPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *SpawnOtherPlayer) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SpawnOtherPlayer) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SpawnOtherPlayer) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *SpawnOtherPlayer) GetRotationY() float32 {
	if x != nil {
		return x.RotationY
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender  string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_GameMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{5}
}

func (x *ChatMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type LoginMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *LoginMessage) Reset() {
	*x = LoginMessage{}
	mi := &file_GameMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginMessage) ProtoMessage() {}

func (x *LoginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginMessage.ProtoReflect.Descriptor instead.
func (*LoginMessage) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{6}
}

func (x *LoginMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type LogoutMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *LogoutMessage) Reset() {
	*x = LogoutMessage{}
	mi := &file_GameMessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutMessage) ProtoMessage() {}

func (x *LogoutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutMessage.ProtoReflect.Descriptor instead.
func (*LogoutMessage) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{7}
}

func (x *LogoutMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type SpawnMonster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Z         float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	MonsterId int32   `protobuf:"varint,4,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
}

func (x *SpawnMonster) Reset() {
	*x = SpawnMonster{}
	mi := &file_GameMessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnMonster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnMonster) ProtoMessage() {}

func (x *SpawnMonster) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnMonster.ProtoReflect.Descriptor instead.
func (*SpawnMonster) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{8}
}

func (x *SpawnMonster) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SpawnMonster) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *SpawnMonster) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

type GameMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*GameMessage_PlayerPosition
	//	*GameMessage_Chat
	//	*GameMessage_Login
	//	*GameMessage_SpawnMyPlayer
	//	*GameMessage_SpawnOtherPlayer
	//	*GameMessage_Logout
	//	*GameMessage_PathTest
	//	*GameMessage_SpawnMonster
	Message isGameMessage_Message `protobuf_oneof:"message"`
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_GameMessage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{9}
}

func (m *GameMessage) GetMessage() isGameMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *GameMessage) GetPlayerPosition() *PlayerPosition {
	if x, ok := x.GetMessage().(*GameMessage_PlayerPosition); ok {
		return x.PlayerPosition
	}
	return nil
}

func (x *GameMessage) GetChat() *ChatMessage {
	if x, ok := x.GetMessage().(*GameMessage_Chat); ok {
		return x.Chat
	}
	return nil
}

func (x *GameMessage) GetLogin() *LoginMessage {
	if x, ok := x.GetMessage().(*GameMessage_Login); ok {
		return x.Login
	}
	return nil
}

func (x *GameMessage) GetSpawnMyPlayer() *SpawnMyPlayer {
	if x, ok := x.GetMessage().(*GameMessage_SpawnMyPlayer); ok {
		return x.SpawnMyPlayer
	}
	return nil
}

func (x *GameMessage) GetSpawnOtherPlayer() *SpawnOtherPlayer {
	if x, ok := x.GetMessage().(*GameMessage_SpawnOtherPlayer); ok {
		return x.SpawnOtherPlayer
	}
	return nil
}

func (x *GameMessage) GetLogout() *LogoutMessage {
	if x, ok := x.GetMessage().(*GameMessage_Logout); ok {
		return x.Logout
	}
	return nil
}

func (x *GameMessage) GetPathTest() *PathTest {
	if x, ok := x.GetMessage().(*GameMessage_PathTest); ok {
		return x.PathTest
	}
	return nil
}

func (x *GameMessage) GetSpawnMonster() *SpawnMonster {
	if x, ok := x.GetMessage().(*GameMessage_SpawnMonster); ok {
		return x.SpawnMonster
	}
	return nil
}

type isGameMessage_Message interface {
	isGameMessage_Message()
}

type GameMessage_PlayerPosition struct {
	PlayerPosition *PlayerPosition `protobuf:"bytes,1,opt,name=player_position,json=playerPosition,proto3,oneof"`
}

type GameMessage_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type GameMessage_Login struct {
	Login *LoginMessage `protobuf:"bytes,3,opt,name=login,proto3,oneof"`
}

type GameMessage_SpawnMyPlayer struct {
	SpawnMyPlayer *SpawnMyPlayer `protobuf:"bytes,4,opt,name=spawnMyPlayer,proto3,oneof"`
}

type GameMessage_SpawnOtherPlayer struct {
	SpawnOtherPlayer *SpawnOtherPlayer `protobuf:"bytes,5,opt,name=spawnOtherPlayer,proto3,oneof"`
}

type GameMessage_Logout struct {
	Logout *LogoutMessage `protobuf:"bytes,6,opt,name=logout,proto3,oneof"`
}

type GameMessage_PathTest struct {
	PathTest *PathTest `protobuf:"bytes,7,opt,name=pathTest,proto3,oneof"`
}

type GameMessage_SpawnMonster struct {
	SpawnMonster *SpawnMonster `protobuf:"bytes,8,opt,name=spawnMonster,proto3,oneof"`
}

func (*GameMessage_PlayerPosition) isGameMessage_Message() {}

func (*GameMessage_Chat) isGameMessage_Message() {}

func (*GameMessage_Login) isGameMessage_Message() {}

func (*GameMessage_SpawnMyPlayer) isGameMessage_Message() {}

func (*GameMessage_SpawnOtherPlayer) isGameMessage_Message() {}

func (*GameMessage_Logout) isGameMessage_Message() {}

func (*GameMessage_PathTest) isGameMessage_Message() {}

func (*GameMessage_SpawnMonster) isGameMessage_Message() {}

var File_GameMessage_proto protoreflect.FileDescriptor

var file_GameMessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x05, 0x4e, 0x61, 0x76,
	0x56, 0x33, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c,
	0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x2d, 0x0a, 0x08,
	0x50, 0x61, 0x74, 0x68, 0x54, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4e,
	0x61, 0x76, 0x56, 0x33, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x0e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x78, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x66, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x66, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x7a, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x66, 0x7a, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x22, 0x58, 0x0a, 0x0d, 0x53, 0x70,
	0x61, 0x77, 0x6e, 0x4d, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x59, 0x22, 0x77, 0x0a, 0x10, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x4f, 0x74, 0x68,
	0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79,
	0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x09, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x22, 0x3f, 0x0a,
	0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x2a,
	0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0d, 0x4c, 0x6f,
	0x67, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x0c, 0x53, 0x70, 0x61, 0x77, 0x6e,
	0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x7a, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x22, 0xc8, 0x03, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x3f, 0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x3b, 0x0a, 0x0d, 0x73, 0x70, 0x61, 0x77, 0x6e,
	0x4d, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x4d, 0x79, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4d, 0x79, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x10, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4f, 0x74, 0x68,
	0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x00, 0x52, 0x10, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4f,
	0x74, 0x68, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x06, 0x6c, 0x6f,
	0x67, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x00, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x61, 0x74,
	0x68, 0x54, 0x65, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x54, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x70,
	0x61, 0x74, 0x68, 0x54, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0c, 0x73, 0x70, 0x61, 0x77, 0x6e,
	0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65,
	0x72, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0b, 0x5a, 0x09,
	0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_GameMessage_proto_rawDescOnce sync.Once
	file_GameMessage_proto_rawDescData = file_GameMessage_proto_rawDesc
)

func file_GameMessage_proto_rawDescGZIP() []byte {
	file_GameMessage_proto_rawDescOnce.Do(func() {
		file_GameMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_GameMessage_proto_rawDescData)
	})
	return file_GameMessage_proto_rawDescData
}

var file_GameMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_GameMessage_proto_goTypes = []any{
	(*NavV3)(nil),            // 0: game.NavV3
	(*PathTest)(nil),         // 1: game.PathTest
	(*PlayerPosition)(nil),   // 2: game.PlayerPosition
	(*SpawnMyPlayer)(nil),    // 3: game.SpawnMyPlayer
	(*SpawnOtherPlayer)(nil), // 4: game.SpawnOtherPlayer
	(*ChatMessage)(nil),      // 5: game.ChatMessage
	(*LoginMessage)(nil),     // 6: game.LoginMessage
	(*LogoutMessage)(nil),    // 7: game.LogoutMessage
	(*SpawnMonster)(nil),     // 8: game.SpawnMonster
	(*GameMessage)(nil),      // 9: game.GameMessage
}
var file_GameMessage_proto_depIdxs = []int32{
	0, // 0: game.PathTest.paths:type_name -> game.NavV3
	2, // 1: game.GameMessage.player_position:type_name -> game.PlayerPosition
	5, // 2: game.GameMessage.chat:type_name -> game.ChatMessage
	6, // 3: game.GameMessage.login:type_name -> game.LoginMessage
	3, // 4: game.GameMessage.spawnMyPlayer:type_name -> game.SpawnMyPlayer
	4, // 5: game.GameMessage.spawnOtherPlayer:type_name -> game.SpawnOtherPlayer
	7, // 6: game.GameMessage.logout:type_name -> game.LogoutMessage
	1, // 7: game.GameMessage.pathTest:type_name -> game.PathTest
	8, // 8: game.GameMessage.spawnMonster:type_name -> game.SpawnMonster
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_GameMessage_proto_init() }
func file_GameMessage_proto_init() {
	if File_GameMessage_proto != nil {
		return
	}
	file_GameMessage_proto_msgTypes[9].OneofWrappers = []any{
		(*GameMessage_PlayerPosition)(nil),
		(*GameMessage_Chat)(nil),
		(*GameMessage_Login)(nil),
		(*GameMessage_SpawnMyPlayer)(nil),
		(*GameMessage_SpawnOtherPlayer)(nil),
		(*GameMessage_Logout)(nil),
		(*GameMessage_PathTest)(nil),
		(*GameMessage_SpawnMonster)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GameMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GameMessage_proto_goTypes,
		DependencyIndexes: file_GameMessage_proto_depIdxs,
		MessageInfos:      file_GameMessage_proto_msgTypes,
	}.Build()
	File_GameMessage_proto = out.File
	file_GameMessage_proto_rawDesc = nil
	file_GameMessage_proto_goTypes = nil
	file_GameMessage_proto_depIdxs = nil
}
